"""updated database

Revision ID: 5670dd2163d3
Revises: 7388ee96dc03
Create Date: 2025-06-12 11:13:59.696850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5670dd2163d3'
down_revision = '7388ee96dc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
